# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit AI Configuration for vNext Schema Definitions
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language settings
language: en-US

# Review settings
reviews:
  # Enable reviews on all branches, not just the default branch
  review_status: true
  # Enable auto reviews on all target branches
  auto_review:
    enabled: true
    # Review all branches including non-default ones
    base_branches:
      - master
      - main
      - develop
      - sonar
      - "release/*"
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
      - "schema/*"
  # Request changes threshold
  request_changes_workflow: false

# What to review
review:
  # Enable review of different file types - focused on JavaScript/JSON Schema project
  include_patterns:
    - "**/*.js"
    - "**/*.ts"
    - "**/*.json"
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.d.ts"
    - "**/package.json"
    - "**/package-lock.json"
    - "**/*.schema.json"
  
  # Skip certain files/directories
  exclude_patterns:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/coverage/**"
    - "**/.nyc_output/**"
    - "**/logs/**"
    - "**/*.log"
    - "**/.DS_Store"
    - "**/Thumbs.db"

# Chat settings
chat:
  # Enable chat functionality
  auto_reply: false

# Early access features
early_access: true